server:
  port: 6001
spring:
  application:
    name: fly-leadnews-admin-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 159.75.89.7:8848
    gateway:
      globalcors:
        cors-configurations: #跨域请求处理
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 平台管理
        - id: admin
          uri: lb://leadnews-admin-lzp
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix= 1
        # user微服务
        - id: user
          uri: lb://leadnews-user-lzp
          predicates:
            - Path=/user/**  #http://localhost:6001/admin/api/v1/channel/list -->http://localhost:9001/api/v1/channel/list
          filters:
            - StripPrefix= 1